openapi: 3.0.1
info:
  title: My CalGPT API           # API の名前
  version: '1.0'                 # バージョン
paths:
  /events:                       # ルート（URL）の指定
    get:                         # GET メソッド：予定取得
      summary: 予定一覧取得
      parameters:
        - in: query
          name: timeMin         # ?timeMin=YYYY-MM-DDThh:mm:ss で絞り込む例
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object     # レスポンスが JSON オブジェクト
    post:                        # POST メソッド：予定作成
      summary: 予定作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object      # リクエストに予定情報の JSON を渡す
      responses:
        '200':
          description: 作成完了
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    oauth2:                     # OAuth2 の設定
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl:      https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/calendar.events: Manage Calendar Events
security:
  - oauth2: [https://www.googleapis.com/auth/calendar.events]
